# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do
  desc "Runs all the tests"
  lane :test do
    gradle(task: "test")
  end

  desc "Submit a new Beta Build to Crashlytics Beta"
  lane :beta do
    gradle(task: "clean assembleRelease")
    crashlytics
  
    # sh "your_script.sh"
    # You can also use other beta testing services here
  end

  desc "Deploy a new version to the Google Play"
  lane :deploy do
    gradle(task: "clean assembleRelease")
    upload_to_play_store
  end

  # For Deployment
  desc "Distribute"
    lane :distribute do
      gradle(task: "clean assembleRelease")
      firebase_app_distribution(
          app: ENV['APP_ID'],
          groups: "testers",
          release_notes: "Lots of amazing new features to test out!"
      )
  end

  desc "Test"
      lane :app_test do
        gradle(task: "clean assembleRelease")
        firebase_app_distribution(
            app: ENV['APP_ID'],
            groups: "devs",
            release_notes: "This is for testing"
        )
    end
end
